
@if($loading)
    

<div class="absolute top-0 bottom-0 left-0 right-0 z-50 bg-white bg-opacity-50">
  <div class="flex items-center justify-center min-h-full border">
    
    <div class="px-2 pt-2 bg-white shadow-lg rounded-xl">
        <div class="loadingio-spinner-spinner-q0i9xaqu9t"><div class="ldio-hcgl2a48rmg">
            <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            </div>
        </div>
    </div>
    
        <style type="text/css">
        @keyframes ldio-hcgl2a48rmg {
          0% { opacity: 1 }
          100% { opacity: 0 }
        }
        .ldio-hcgl2a48rmg div {
          left: 45px;
          top: 4.5px;
          position: absolute;
          animation: ldio-hcgl2a48rmg linear 1s infinite;
          background: #521622;
          width: 10px;
          height: 21px;
          border-radius: 5px / 10.5px;
          transform-origin: 5px 45.5px;
        }.ldio-hcgl2a48rmg div:nth-child(1) {
          transform: rotate(0deg);
          animation-delay: -0.9166666666666666s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(2) {
          transform: rotate(30deg);
          animation-delay: -0.8333333333333334s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(3) {
          transform: rotate(60deg);
          animation-delay: -0.75s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(4) {
          transform: rotate(90deg);
          animation-delay: -0.6666666666666666s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(5) {
          transform: rotate(120deg);
          animation-delay: -0.5833333333333334s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(6) {
          transform: rotate(150deg);
          animation-delay: -0.5s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(7) {
          transform: rotate(180deg);
          animation-delay: -0.4166666666666667s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(8) {
          transform: rotate(210deg);
          animation-delay: -0.3333333333333333s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(9) {
          transform: rotate(240deg);
          animation-delay: -0.25s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(10) {
          transform: rotate(270deg);
          animation-delay: -0.16666666666666666s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(11) {
          transform: rotate(300deg);
          animation-delay: -0.08333333333333333s;
          background: #521622;
        }.ldio-hcgl2a48rmg div:nth-child(12) {
          transform: rotate(330deg);
          animation-delay: 0s;
          background: #521622;
        }
        .loadingio-spinner-spinner-q0i9xaqu9t {
          width: 40px;
          height: 40px;
          display: inline-block;
          overflow: hidden;
          background: none;
        }
        .ldio-hcgl2a48rmg {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(0.4);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-hcgl2a48rmg div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
        </style>
  </div>


        
</div>
@endif